### ISSUE TITLE
File path problem

### ISSUE THREAD

**Issue by hlh199603** [ucas-vg/TinyBenchmark#14]
i have modified path in \${TinyBenchmark}/tiny_benchmark/maskrcnn_benchmark/config/paths_catalog.py 
But there are still path problems，What should I do？
![Uploading QQ图片20200428233053.png…]()
[error]：No such file or directory:
'/home/$user/TinyBenchmark/dataset/tiny_set/erase_with_uncertain_dataset/annotations/corner/task/tiny_set_train_sw640_sh512_all.json'

**Comment by yinglang** [comment]
I can't see the image you uploaded. I guess your problem may caused by wrong path you have set.
you may need download dataset in [section](https://github.com/ucas-vg/TinyBenchmark#download-link) in your disk, assume you download in /home/your_name/TinyBenchmark/dataset/tiny_set, and then you just modify     
`DATA_DIR = "/home/$user/TinyBenchmark/dataset"`
to 
`DATA_DIR = "/home/your_name/TinyBenchmark/dataset/"`
