### ISSUE TITLE
Data annotation problems

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#19]
Hi! When I make my own dataset, the label of the object needs to be like instance segmentation, or just bbox (x1, y1, x2, y2).
Because I see that your label has both "segmentation" and "bbox". Would you like to use the "segmentation" label during training?

**Comment by yinglang** [comment]
the 'segmentation' is not use in our method, but normally we will try to keep same format with coco standard to avoid some unnecessary bugs. so 'segmentation' is set to [[x1,y1,x2, y1, x2,y2, x1, y2]]('segmentation'[2*I:2*I+2] is the i-th corner point of the segmentation). and another point, 'box' is (x1, y1, w, h) instead of (x1, y1, x2, y2), here are an [example(section 2.1 annotation-format)](https://github.com/ucas-vg/TinyBenchmark/tree/master/dataset#21-annotation-format-) may help you

**Comment by Pluto1314** [comment]
ok，thanks！
The issue will be close！
