### ISSUE TITLE
About Change of Evaluation

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#41]
Hi. I have some questions about your paper.

1. In your paper
![image](https://user-images.githubusercontent.com/47765770/97099515-d5205880-16c4-11eb-9cc9-e54fb62ee644.png)

AP_tiny_50 = 43.55 for detector (Faster RCNN), AP_tiny_50 = 47.29 when use MSM COCO pretrained.
"AP_tiny_50 = 43.55 for detector" does it mean that the original network is used for training instead of the MSM method?

2. In your github
![image](https://user-images.githubusercontent.com/47765770/97099601-d8681400-16c5-11eb-92cb-a64d66fe2b5c.png)
![image](https://user-images.githubusercontent.com/47765770/97099594-cab28e80-16c5-11eb-9652-352bdb524340.png)

AP_tiny_50 = 47.35 for detector (Faster RCNN), AP_tiny_50 = 51.33 when use SM COCO pretrained.
"AP_tiny_50 = 47.35 for detector" does it mean that the original network is used for training instead of the SM method?

3. IOD

Do "AP_tiny_50 = 43.55 for detector" and "AP_tiny_50 = 47.35 for detector" both use the original Faster RCNN (not use SM or MSM)? Is the difference between them in the evaluation method? The latter uses the IOD method for evaluation?

![image](https://user-images.githubusercontent.com/47765770/97099672-7e1b8300-16c6-11eb-8b8e-fc4ed6be56fa.png)

Does "AP_tiny_50 = 43.55 for detector" use IOD, and "AP_tiny_50 = 47.35 for detector" does not use IOD?

![image](https://user-images.githubusercontent.com/47765770/97099741-62fd4300-16c7-11eb-94d0-a431dbd3e19a.png)
But it is mentioned in your paper that "AP_tiny_50 = 47.29" seems to use IOD.

Is there any difference between these two sets of experiments?
Sorry to disturb you and look forward to your reply, thank you！

**Comment by yinglang** [comment]
Thanks the good questions, the question are very detail and we are very necessary to answer.
1. in paper, old evaluation is applied, "AP_tiny_50 = 43.55" do mean that the original network is used for training instead of the MSM method, it is same as the first line in table7
2. in GitHub, performance of new evaluation also public, the "AP_tiny_50 = 47.35" you showed is the original network is used for training instead of the SM method which apply new evaluation.
3. your statement is partly right. for the old evaluation, some "ignore" area and "uncertain" area are not treated as ignore rightly， which mean detection result matched some 'ignore' area still be treated as false positive, which is not properly, so we update the evaluation, And in the new evaluation, all ignore area and uncertain  area are treated properly.
Besides, both of the new and old evaluation use IOD evaluation for ignore area.
if there are still some questions, please write here, we will answer when we see.

**Comment by Pluto1314** [comment]
Thank you very much for your detailed reply.
I currently use your datasets for academic research, but I don't know which of your results should be cited when citing your paper.

Or do you have an old version of the evaluation code? Because in my method, I can only use the new version of the evaluation code provided by you for testing, and cannot compare with your paper.

Sorry to trouble you again!

**Comment by yinglang** [comment]
ok.  we suggest the new evaluation should be used for cite cause it is more reasonable.  we also have some new works under review on the dataset，in these works，we also use the results in new evaluation. 发自我的华为手机-------- 原始邮件 --------发件人： Pluto1314 <notifications@github.com>日期： 2020年10月26日周一 晚上10:28收件人： ucas-vg/TinyBenchmark <TinyBenchmark@noreply.github.com>抄送： yinglang <y19941010@126.com>, Comment <comment@noreply.github.com>主    题： Re: [ucas-vg/TinyBenchmark] some question about your paper (#41)
Thank you very much for your detailed reply.
I currently use your datasets for academic research, but I don't know which of your results should be cited when citing your paper.
Or do you have an old version of the evaluation code? Because in my method, I can only use the new version of the evaluation code provided by you for testing, and cannot compare with your paper.
Sorry to trouble you again!

**Comment by Pluto1314** [comment]
ok，I get it. Thank you for your reply ！





------------------ Original ------------------

**Comment by yinglang** [comment]
ok, it seems no more questions, I will close the issue.
