### ISSUE TITLE
Training my own dataset

### ISSUE THREAD

**Issue by Pluto1314** [ucas-vg/TinyBenchmark#8]
Hello, I think this is a nice work.
I have a question, can this Tinybenchmark use my own data set to detect the target I need?

For example, I want to detect different types of cars (there are probably 4 types of targets), but they are all very small targets.

What do I need to change? Can you give me some suggestions? Thank you!

**Comment by yinglang** [comment]
yes, TinyBenchmark can use on your own dataset.
1. your need to turn your dataset annotation format to coco-style and add to [path_catalog.py](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/maskrcnn_benchmark/config/paths_catalog.py).
if you need cut image as input while evaluation, make it [corner dataset anotation](https://github.com/ucas-vg/TinyBenchmark/tree/master/dataset#2.3), otherwise set TEST.MERGE_RESULTS as False and TEST.MERGE_GT_FILE:"" in yaml config file.
2. the main adjustments are same as common detection setting such as anchor setting, lr policy.
3. if you want pretrain on COCO with scale match, you need open Scale Match on config file.

maybe we need to release a tutorials for that in future.

**Comment by Pluto1314** [comment]
Thank you for your reply. I'll have a try.
I'm looking forward to your update.

**Comment by Pluto1314** [comment]
@yinglang hi，how can i pretrain on COCO with scale match and get the COCO pretrained weights on my own dataset？Can you give me some suggestions? Thank you!

**Comment by zhaoxin111** [comment]
> @yinglang hi，how can i pretrain on COCO with scale match and get the COCO pretrained weights on my own dataset？Can you give me some suggestions? Thank you!

Have you trained your data successfully? I'd like to try it

**Comment by yinglang** [comment]
we have add a simple steps for train with MSM/SM on your own dataset [here](https://github.com/ucas-vg/TinyBenchmark/blob/master/tiny_benchmark/configs/TinyCOCO/Readme.md#train-scale-match-coco-or-monotonous-scale-match-coco-for-your-dataset)

**Comment by Fly-dream12** [comment]
Thanks for your update, by the way, I wonder how to generate the corresponding json file (such as SCALE_MATCH.SOURCE_ANNO_FILE and SCALE_MATCH.TARGET_ANNO_FILE), according to my own dataset ? @yinglang
